# -*- coding: utf-8 -*-
"""Generate contacts.xlsx — IT helpdesk contact directory (~300 rows, banking).
Rerun anytime:  python generate_contacts.py
"""
import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill

IT_EMAIL = "xuanbach68739301@gmail.com"

DEPARTMENTS = {
    "P.Hỗ trợ Công nghệ": ("Nguyễn Văn An", "Trưởng phòng IT", IT_EMAIL, "Teams: IT Support", "028-3821-1001"),
    "P.Hạ tầng & Mạng": ("Trần Thị Bình", "Trưởng phòng Hạ tầng", IT_EMAIL, "Teams: Network Team", "028-3821-1002"),
    "P.Bảo mật Thông tin": ("Lê Hoàng Cường", "Trưởng phòng Bảo mật", IT_EMAIL, "Teams: InfoSec Team", "028-3821-1003"),
    "P.Hệ thống Core Banking": ("Phạm Minh Dũng", "Trưởng phòng Core", IT_EMAIL, "Teams: Core Banking", "028-3821-1004"),
    "P.Thanh toán Quốc tế": ("Vũ Thanh Hà", "Trưởng phòng TTQT", "ha.vt@bank.com.vn", "Teams: SWIFT Team", "028-3821-1005"),
    "P.ATM & Thẻ": ("Đặng Ngọc Em", "Trưởng phòng Thẻ", "em.dn@bank.com.vn", "Teams: Card & ATM", "028-3821-1006"),
    "P.Kế toán": ("Bùi Thị Phượng", "Trưởng phòng Kế toán", "phuong.bt@bank.com.vn", "Teams: Accounting", "028-3821-1007"),
    "P.Nhân sự": ("Hồ Văn Giang", "Trưởng phòng NS", "giang.hv@bank.com.vn", "Teams: HR Team", "028-3821-1008"),
    "P.Dữ liệu & BI": ("Mai Thị Hồng", "Trưởng phòng Dữ liệu", IT_EMAIL, "Teams: Data & BI", "028-3821-1009"),
    "P.Phát triển Phần mềm": ("Phan Quang Khôi", "Trưởng phòng Dev", IT_EMAIL, "Teams: Dev Team", "028-3821-1010"),
    "P.Vận hành": ("Lương Thanh Long", "Trưởng phòng Vận hành", IT_EMAIL, "Teams: Ops Team", "028-3821-1011"),
    "P.Ngân hàng Số": ("Đỗ Thị Lam", "Trưởng phòng NH Số", IT_EMAIL, "Teams: Digital Banking", "028-3821-1012"),
    "P.Tín dụng": ("Ng6 Cao Thị Mai", "Trưởng phòng Tín dụng", "mai6.ct@bank.com.vn", "Teams: Credit Team", "028-3821-1013"),
    "P.Quản lý Rủi ro": ("Vương Thị Nga", "Trưởng phòng QLRR", "nga.vt@bank.com.vn", "Teams: Risk Team", "028-3821-1014"),
    "P.Kiểm soát Nội bộ": ("Lý Thị Oanh", "Trưởng phòng KSNB", "oanh.lt@bank.com.vn", "Teams: Audit Team", "028-3821-1015"),
    "P.Giao dịch": ("Phan Thị Phúc", "Trưởng phòng Giao dịch", "phuc.pt@bank.com.vn", "Teams: Teller Team", "028-3821-1016"),
    "P.Kho quỹ": ("Hoàng Thị Quỳnh", "Trưởng phòng Kho quỹ", "quynh.ht@bank.com.vn", "Teams: Treasury Ops", "028-3821-1017"),
    "P.Pháp chế": ("Ngô Văn Sơn", "Trưởng phòng Pháp chế", "son.nv@bank.com.vn", "Teams: Legal Team", "028-3821-1018"),
    "P.AML": ("Dương Thị Thảo", "Trưởng phòng AML", "thao.dt@bank.com.vn", "Teams: AML Team", "028-3821-1019"),
    "P.Chăm sóc Khách hàng": ("Lâm Thị Uyên", "Trưởng phòng CSKH", "uyen.lt@bank.com.vn", "Teams: Customer Care", "028-3821-1020"),
    "P.Marketing": ("Trịnh Văn Vũ", "Trưởng phòng Marketing", "vu.tv@bank.com.vn", "Teams: Marketing", "028-3821-1021"),
    "P.Mua hàng": ("Ân Thị Vy", "Trưởng phòng Mua hàng", "vy.at@bank.com.vn", "Teams: Procurement", "028-3821-1022"),
    "P.Tài chính Đầu tư": ("Tạ Văn Xuân", "Trưởng phòng TCĐT", "xuan.tv@bank.com.vn", "Teams: Treasury", "028-3821-1023"),
    "P.Phát triển Sản phẩm": ("Lê Thị Yến", "Trưởng phòng PTSP", "yen.lt@bank.com.vn", "Teams: Product Team", "028-3821-1024"),
}

ROWS = [
    # === Máy tính / Hardware (15) ===
    ("Máy tính", "máy tính không bật lỗi khởi động", "Máy trạm/không nguồn, không khởi động được", "P.Công nghệ Thông tin"),
    ("Máy tính", "máy tính chậm đơ treo lag", "Máy chạy chậm, đơ, treo khi dùng", "P.Công nghệ Thông tin"),
    ("Máy tính", "laptop hỏng màn hình đen", "Laptop không lên màn hình", "P.Công nghệ Thông tin"),
    ("Máy tính", "màn hình không hiển thị", "Màn hình desktop không ra hình", "P.Công nghệ Thông tin"),
    ("Máy tính", "bàn phím chuột hỏng", "Bàn phím/chuột không hoạt động", "P.Công nghệ Thông tin"),
    ("Máy tính", "ổ cứng đầy hết dung lượng", "Disk full, không lưu được file", "P.Công nghệ Thông tin"),
    ("Máy tính", "RAM lỗi báo beep", "RAM hỏng, máy báo tiếng beep", "P.Hạ tầng & Mạng"),
    ("Máy tính", "cài đặt phần mềm trên máy", "Yêu cầu cài phần mềm mới", "P.Công nghệ Thông tin"),
    ("Máy tính", "cấp phát máy mới đổi máy", "Xin máy mới / đổi máy tính", "P.Công nghệ Thông tin"),
    ("Máy tính", "bảo trì vệ sinh máy tính", "Bảo trì định kỳ máy trạm", "P.Công nghệ Thông tin"),
    ("Máy tính", "máy tính nhiễm virus malware", "Máy bị virus, cần quét và xử lý", "P.Bảo mật Thông tin"),
    ("Máy tính", "webcam không hoạt động", "Webcam không chạy cho họp online", "P.Công nghệ Thông tin"),
    ("Máy tính", "tai nghe micro lỗi", "Tai nghe/micro không chạy cho họp online", "P.Công nghệ Thông tin"),
    ("Máy tính", "máy tính restart tự động", "Máy tự restart/tắt đột ngột", "P.Công nghệ Thông tin"),
    ("Máy tính", "cập nhật windows lỗi", "Windows update lỗi/treO", "P.Công nghệ Thông tin"),
    # === Mạng / Network (12) ===
    ("Mạng", "mất mạng không vào internet", "Mất kết nối internet hoàn toàn", "P.Hạ tầng & Mạng"),
    ("Mạng", "wifi chậm không kết nối", "WiFi yếu/chậm/không vào được", "P.Hạ tầng & Mạng"),
    ("Mạng", "vpn không vào lỗi đăng nhập", "VPN không kết nối / sai pass", "P.Bảo mật Thông tin"),
    ("Mạng", "lan cáp mạng đứt", "Cáp mạng/LAN đứt, mất tín hiệu", "P.Hạ tầng & Mạng"),
    ("Mạng", "ip conflict trùng ip", "Trùng địa chỉ IP trên mạng", "P.Hạ tầng & Mạng"),
    ("Mạng", "tốc độ mạng chậm bandwidth", "Băng thông thấp, mạng chậm", "P.Hạ tầng & Mạng"),
    ("Mạng", "firewall chặn truy cập", "Firewall block website/ứng dụng", "P.Bảo mật Thông tin"),
    ("Mạng", "dns lỗi không phân giải", "DNS không phân giải được tên miền", "P.Hạ tầng & Mạng"),
    ("Mạng", "mạng chi nhánh mất kết nối HO", "Chi nhánh mất kết nối về HO", "P.Hạ tầng & Mạng"),
    ("Mạng", "load balancer lỗi", "Load balancer phân phối sai", "P.Hạ tầng & Mạng"),
    ("Mạng", "switch port lỗi", "Port switch hỏng, không link", "P.Hạ tầng & Mạng"),
    ("Mạng", "routing lỗi không đi", "Routing sai, traffic không đi đúng đường", "P.Hạ tầng & Mạng"),
    # === Email / Outlook (10) ===
    ("Email", "không gửi nhận email", "Email không gửi/nhận được", "P.Công nghệ Thông tin"),
    ("Email", "email đầy hết quota", "Hộp thư đầy, vượt dung lượng", "P.Công nghệ Thông tin"),
    ("Email", "outlook lỗi không mở", "Outlook crash/không mở được", "P.Công nghệ Thông tin"),
    ("Email", "quên mật khẩu email", "Reset mật khẩu email", "P.Bảo mật Thông tin"),
    ("Email", "email spam phishing lừa đảo", "Nhận email nghi ngờ lừa đảo", "P.Bảo mật Thông tin"),
    ("Email", "cấu hình email điện thoại", "Cài email trên mobile", "P.Công nghệ Thông tin"),
    ("Email", "email gửi chậm delay", "Email gửi bị chậm/trễ", "P.Công nghệ Thông tin"),
    ("Email", "email đính kèm file lớn", "Không gửi được file đính kèm lớn", "P.Công nghệ Thông tin"),
    ("Email", "outlook rule không chạy", "Rule auto-forward không hoạt động", "P.Công nghệ Thông tin"),
    ("Email", "email group alias lỗi", "Group email/alias không nhận được", "P.Công nghệ Thông tin"),
    # === SWIFT / Thanh toán quốc tế (15) ===
    ("SWIFT", "swift message bị NAK", "Tin nhắn SWIFT bị từ chối (NAK)", "P.Thanh toán Quốc tế"),
    ("SWIFT", "swift ACK chậm", "ACK xác nhận SWIFT chậm", "P.Thanh toán Quốc tế"),
    ("SWIFT", "swift kết nối mất SAG lỗi", "SWIFT Alliance Gateway mất kết nối", "P.Thanh toán Quốc tế"),
    ("SWIFT", "chuyển tiền quốc tế lỗi", "Lệnh chuyển tiền QT bị lỗi", "P.Thanh toán Quốc tế"),
    ("SWIFT", "swift key BIC code sai", "BIC/key sai, tin nhắn bị reject", "P.Thanh toán Quốc tế"),
    ("SWIFT", "swift message duplicate trùng", "Tin nhắn SWIFT bị trùng/gửi 2 lần", "P.Thanh toán Quốc tế"),
    ("SWIFT", "reversal hủy lệnh swift", "Hủy/reversal lệnh SWIFT", "P.Thanh toán Quốc tế"),
    ("SWIFT", "swift queue stuck kẹt hàng", "Hàng đợi SWIFT bị kẹt", "P.Thanh toán Quốc tế"),
    ("SWIFT", "đối soát swift reconciliation", "Đối soát giao dịch SWIFT", "P.Thanh toán Quốc tế"),
    ("SWIFT", "cấu hình swift alliance access", "Cấu hình SWIFT Alliance Access", "P.Thanh toán Quốc tế"),
    ("SWIFT", "swift MT103 MT202 lỗi", "Tin nhắn MT103/MT202 lỗi định dạng", "P.Thanh toán Quốc tế"),
    ("SWIFT", "swift correspondent bank lỗi", "Ngân hàng đại lý (correspondent) lỗi", "P.Thanh toán Quốc tế"),
    ("SWIFT", "swift RMA lỗi", "RMA (Relationship Management Application) lỗi", "P.Thanh toán Quốc tế"),
    ("SWIFT", "nostro vostro đối soát", "Đối soát tài khoản Nostro/Vostro", "P.Thanh toán Quốc tế"),
    ("SWIFT", "swift sanction screening", "Kiểm tra sanction trên SWIFT", "P.AML"),
    # === Core Banking (15) ===
    ("Core Banking", "core banking chậm treo", "Hệ thống core chậm/treo", "P.Hệ thống Core Banking"),
    ("Core Banking", "core không đăng nhập được", "Không login được core banking", "P.Hệ thống Core Banking"),
    ("Core Banking", "giao dịch core lỗi fail", "Giao dịch trên core bị fail", "P.Hệ thống Core Banking"),
    ("Core Banking", "cập nhật số dư chậm", "Số dư cập nhật chậm/bất đồng bộ", "P.Hệ thống Core Banking"),
    ("Core Banking", "batch job core fail", "Batch job core banking thất bại", "P.Vận hành"),
    ("Core Banking", "restore backup core", "Khôi phục/sao lưu core banking", "P.Hệ thống Core Banking"),
    ("Core Banking", "báo cáo core lỗi", "Báo cáo từ core bị lỗi/sai số liệu", "P.Hệ thống Core Banking"),
    ("Core Banking", "cấu hình sản phẩm core", "Cấu hình sản phẩm/lãi suất trên core", "P.Hệ thống Core Banking"),
    ("Core Banking", "core end of day EOD chậm", "EOD (end of day) chạy chậm/lỗi", "P.Vận hành"),
    ("Core Banking", "core SOD lỗi", "SOD (start of day) lỗi", "P.Vận hành"),
    ("Core Banking", "core posting sai bút toán", "Bút toán sai trên core", "P.Hệ thống Core Banking"),
    ("Core Banking", "core revert giao dịch", "Revert/hủy giao dịch trên core", "P.Hệ thống Core Banking"),
    ("Core Banking", "core limit hạn mức lỗi", "Hạn mức tín dụng trên core sai", "P.Hệ thống Core Banking"),
    ("Core Banking", "core GL tổng tài khoản", "GL (General Ledger) không cân", "P.Hệ thống Core Banking"),
    ("Core Banking", "core param tham số lỗi", "Tham số cấu hình core bị sai", "P.Hệ thống Core Banking"),
    # === ATM / Thẻ (15) ===
    ("ATM & Thẻ", "atm nuốt thẻ kẹt thẻ", "ATM nuốt/kẹt thẻ khách", "P.ATM & Thẻ"),
    ("ATM & Thẻ", "atm không trả tiền lỗi rút", "ATM không xuất tiền", "P.ATM & Thẻ"),
    ("ATM & Thẻ", "thẻ bị khóa block", "Thẻ bị khóa/block", "P.ATM & Thẻ"),
    ("ATM & Thẻ", "thẻ hết hạn gia hạn", "Thẻ hết hạn, cần gia hạn", "P.ATM & Thẻ"),
    ("ATM & Thẻ", "pos lỗi không quẹt", "Máy POS không quẹt thẻ được", "P.ATM & Thẻ"),
    ("ATM & Thẻ", "quên pin khóa pin", "Quên/khóa mã PIN thẻ", "P.ATM & Thẻ"),
    ("ATM & Thẻ", "giao dịch thẻ trừ sai", "Thẻ bị trừ tiền sai số", "P.ATM & Thẻ"),
    ("ATM & Thẻ", "kích hoạt thẻ mới", "Kích hoạt thẻ mới phát hành", "P.ATM & Thẻ"),
    ("ATM & Thẻ", "atm hết tiền nạp", "ATM hết tiền mặt, cần nạp", "P.Kho quỹ"),
    ("ATM & Thẻ", "thẻ từ chối giao dịch decline", "Thẻ bị decline khi giao dịch", "P.ATM & Thẻ"),
    ("ATM & Thẻ", "mã thẻ sai invalid card", "Thẻ invalid/expired", "P.ATM & Thẻ"),
    ("ATM & Thẻ", "thẻ contactless lỗi", "Tap-to-pay không hoạt động", "P.ATM & Thẻ"),
    ("ATM & Thẻ", "atm màn hình lỗi hỏng", "Màn hình ATM hỏng/không hiển thị", "P.ATM & Thẻ"),
    ("ATM & Thẻ", "thẻ bị clone sao chép", "Nghi ngờ thẻ bị clone/sao chép", "P.Bảo mật Thông tin"),
    ("ATM & Thẻ", "báo cáo giao dịch ATM", "Yêu cầu báo cáo giao dịch ATM", "P.ATM & Thẻ"),
    # === Bảo mật / Security (12) ===
    ("Bảo mật", "tài khoản bị khóa lock", "Tài khoản AD/email bị khóa", "P.Bảo mật Thông tin"),
    ("Bảo mật", "quên mật khẩu reset password", "Yêu cầu reset mật khẩu", "P.Bảo mật Thông tin"),
    ("Bảo mật", "2fa otp không nhận", "Không nhận OTP/2FA", "P.Bảo mật Thông tin"),
    ("Bảo mật", "nghi ngờ hack xâm nhập", "Nghi ngờ tài khoản bị xâm nhập", "P.Bảo mật Thông tin"),
    ("Bảo mật", "virus malware máy", "Máy nhiễm virus/malware", "P.Bảo mật Thông tin"),
    ("Bảo mật", "email lừa đảo phishing", "Báo cáo email phishing", "P.Bảo mật Thông tin"),
    ("Bảo mật", "usb thiết bị bị chặn", "USB/thiết bị ngoài bị policy chặn", "P.Bảo mật Thông tin"),
    ("Bảo mật", "token RSA hard token lỗi", "Token RSA/hard token không hoạt động", "P.Bảo mật Thông tin"),
    ("Bảo mật", "mật khẩu yếu weak password", "Cảnh báo mật khẩu yếu", "P.Bảo mật Thông tin"),
    ("Bảo mật", "session timeout liên tục", "Session bị timeout liên tục", "P.Bảo mật Thông tin"),
    ("Bảo mật", "data loss prevention DLP", "DLP chặn gửi file ra ngoài", "P.Bảo mật Thông tin"),
    ("Bảo mật", "endpoint protection lỗi", "Endpoint protection/antivirus lỗi", "P.Bảo mật Thông tin"),
    # === Phần mềm / Software (15) ===
    ("Phần mềm", "office word excel lỗi", "Word/Excel/PowerPoint lỗi", "P.Công nghệ Thông tin"),
    ("Phần mềm", "phần mềm ERP lỗi", "Hệ thống ERP bị lỗi", "P.Phát triển Phần mềm"),
    ("Phần mềm", "phần mềm CRM lỗi", "Hệ thống CRM bị lỗi", "P.Phát triển Phần mềm"),
    ("Phần mềm", "phần mềm kế toán SAP lỗi", "SAP/phần mềm kế toán lỗi", "P.Kế toán"),
    ("Phần mềm", "cài đặt phần mềm mới", "Yêu cầu cài phần mềm", "P.Công nghệ Thông tin"),
    ("Phần mềm", "license phần mềm hết hạn", "License hết hạn cần gia hạn", "P.Công nghệ Thông tin"),
    ("Phần mềm", "phần mềm không mở crash", "Phần mềm crash/không mở được", "P.Công nghệ Thông tin"),
    ("Phần mềm", "cập nhật phần mềm", "Update phiên bản phần mềm", "P.Công nghệ Thông tin"),
    ("Phần mềm", "tích hợp API hệ thống", "Tích hợp/API giữa các hệ thống", "P.Phát triển Phần mềm"),
    ("Phần mềm", "lỗi version compatibility", "Xung đột phiên bản phần mềm", "P.Phát triển Phần mềm"),
    ("Phần mềm", "phần mềm signature ký số", "Phần mềm ký số/chữ ký điện tử lỗi", "P.Phát triển Phần mềm"),
    ("Phần mềm", "phần mềm OCR lỗi", "OCR nhận dạng văn bản lỗi", "P.Phát triển Phần mềm"),
    ("Phần mềm", "phần mềm eKYC lỗi", "eKYC xác thực khách hàng lỗi", "P.Ngân hàng Số"),
    ("Phần mềm", "phần mềm scoring credit điểm", "Scoring/credit điểm lỗi", "P.Phát triển Phần mềm"),
    ("Phần mềm", "phần mềm workflow duyệt", "Workflow duyệt tín dụng lỗi", "P.Phát triển Phần mềm"),
    # === Server / DB (12) ===
    ("Server/DB", "server down sập", "Server sập/không truy cập", "P.Hạ tầng & Mạng"),
    ("Server/DB", "database lỗi không truy cập", "DB không kết nối được", "P.Dữ liệu & BI"),
    ("Server/DB", "database chậm query timeout", "Query chậm/timeout", "P.Dữ liệu & BI"),
    ("Server/DB", "backup fail không backup", "Backup thất bại", "P.Vận hành"),
    ("Server/DB", "restore dữ liệu", "Khôi phục dữ liệu", "P.Vận hành"),
    ("Server/DB", "disk full server", "Disk server đầy", "P.Hạ tầng & Mạng"),
    ("Server/DB", "cpu ram server cao", "Server quá tải CPU/RAM", "P.Hạ tầng & Mạng"),
    ("Server/DB", "log server đầy", "Log file đầy ổ cứng", "P.Vận hành"),
    ("Server/DB", "database deadlock", "DB deadlock, giao dịch kẹt", "P.Dữ liệu & BI"),
    ("Server/DB", "database replication lag", "Replication DB bị lag", "P.Dữ liệu & BI"),
    ("Server/DB", "database index rebuild", "Cần rebuild index DB", "P.Dữ liệu & BI"),
    ("Server/DB", "server certificate hết hạn", "SSL/TLS certificate hết hạn", "P.Bảo mật Thông tin"),
    # === Website / Portal / Mobile (12) ===
    ("Website/App", "website không vào được", "Website ngân hàng không truy cập", "P.Phát triển Phần mềm"),
    ("Website/App", "internet banking lỗi", "IBanking lỗi/không vào được", "P.Phát triển Phần mềm"),
    ("Website/App", "mobile app lỗi crash", "App mobile crash/lỗi", "P.Phát triển Phần mềm"),
    ("Website/App", "portal nhân sự không vào", "Portal HR không truy cập", "P.Nhân sự"),
    ("Website/App", "lỗi đăng nhập portal", "Không login được portal", "P.Bảo mật Thông tin"),
    ("Website/App", "cập nhật nội dung website", "Đăng/sửa nội dung website", "P.Phát triển Phần mềm"),
    ("Website/App", "mobile app không update", "App không update được phiên bản mới", "P.Ngân hàng Số"),
    ("Website/App", "QR pay lỗi", "QR pay không hoạt động", "P.Ngân hàng Số"),
    ("Website/App", "soft token app lỗi", "Soft token trên app lỗi", "P.Ngân hàng Số"),
    ("Website/App", "faceid vân tay lỗi", "FaceID/vân tay không xác thực được", "P.Ngân hàng Số"),
    ("Website/App", "liên kết tài khoản bank", "Liên kết tài khoản ngân hàng khác lỗi", "P.Ngân hàng Số"),
    ("Website/App", "open API tích hợp lỗi", "Open API lỗi/không gọi được", "P.Ngân hàng Số"),
    # === HR / Nhân sự (8) ===
    ("Nhân sự; sự", "phần mềm chấm công lỗi", "Chấm công lỗi/không vào được", "P.Nhân sự"),
    ("Nhân sự", "email nhân sự hợp đồng", "Hỏi về hợp đồng/chính sách NS", "P.Nhân sự"),
    ("Nhân sự", "cấp tài khoản nhân viên mới", "Tạo tài khoản cho NV mới", "P.Công nghệ Thông tin"),
    ("Nhân sự", "khóa tài khoản nghỉ việc", "Khóa tài khoản NV nghỉ việc", "P.Bảo mật Thông tin"),
    ("Nhân sự", "đổi thông tin cá nhân", "Cập nhật thông tin cá nhân", "P.Nhân sự"),
    ("Nhân sự", "bảng lương lỗi", "Bảng lương sai/không nhận được", "P.Nhân sự"),
    ("Nhân sự", "đào tạo nội bộ đăng ký", "Đăng ký khóa đào tạo nội bộ", "P.Nhân sự"),
    ("Nhân sự", "nghỉ phép annual leave", "Xin nghỉ phép/duyệt annual leave", "P.Nhân sự"),
    # === Kế toán / Finance (8) ===
    ("Kế toán", "phần mềm kế toán lỗi", "Phần mềm KT lỗi/không vào", "P.Kế toán"),
    ("Kế toán", "báo cáo tài chính sai", "Báo cáo TC/số liệu sai", "P.Kế toán"),
    ("Kế toán", "duyệt chi thanh toán nội bộ", "Duyệt chi/thanh toán nội bộ", "P.Kế toán"),
    ("Kế toán", "hóa đơn điện tử lỗi", "HĐĐT lỗi/không xuất được", "P.Kế toán"),
    ("Kế toán", "đối soát ngân sách", "Đối soát ngân sách chi tiêu", "P.Kế toán"),
    ("Kế toán", "báo cáo thuế", "Báo cáo thuế/KK khai thuế", "P.Kế toán"),
    ("Kế toán", "tài khoản 9999 không cân", "TK 9999 không cân đối", "P.Kế toán"),
    ("Kế toán", "phân bổ chi phí", "Phân bổ chi phí sai", "P.Kế toán"),
    # === Cloud / VNG Cloud (6) ===
    ("Cloud", "vng cloud server không truy cập", "Máy chủ VNG Cloud không vào", "P.Hạ tầng & Mạng"),
    ("Cloud", "tạo xóa máy chủ cloud", "Yêu cầu tạo/xóa server cloud", "P.Hạ tầng & Mạng"),
    ("Cloud", "cloud billing chi phí", "Hỏi chi phí/billing cloud", "P.Kế toán"),
    ("Cloud", "object storage s3 lỗi", "Object storage/S3 lỗi", "P.Hạ tầng & Mạng"),
    ("Cloud", "cloud firewall security group", "Security group/firewall cloud lỗi", "P.Bảo mật Thông tin"),
    ("Cloud", "cloud load balancer lỗi", "Load balancer cloud không phân phối", "P.Hạ tầng & Mạng"),
    # === In / Scan / VoIP (8) ===
    ("In/Scan/VoIP", "máy in lỗi không in", "Máy in không in được", "P.Công nghệ Thông tin"),
    ("In/Scan/VoIP", "máy in kẹt giấy", "Máy in kẹt giấy", "P.Công nghệ Thông tin"),
    ("In/Scan/VoIP", "scanner máy scan lỗi", "Máy scan không hoạt động", "P.Công nghệ Thông tin"),
    ("In/Scan/VoIP", "điện thoại bàn voip lỗi", "ĐT bàn/VoIP không gọi được", "P.Hạ tầng & Mạng"),
    ("In/Scan/VoIP", "fax lỗi", "Máy fax không gửi/nhận", "P.Vận hành"),
    ("In/Scan/VoIP", "máy in mạng không kết nối", "Máy in network không kết nối", "P.Công nghệ Thông tin"),
    ("In/Scan/VoIP", "máy in driver lỗi", "Driver máy in lỗi/cần cài lại", "P.Công nghệ Thông tin"),
    ("In/Scan/VoIP", "headset voip lỗi", "Headset VoIP không nghe được", "P.Công nghệ Thông tin"),
    # === Tín dụng / Lending (18) ===
    ("Tín dụng", "tạo hồ sơ khoản vay lỗi", "Tạo hồ sơ vay trên hệ thống lỗi", "P.Tín dụng"),
    ("Tín dụng", "duyệt tín dụng chậm", "Phê duyệt tín dụng chậm/treo", "P.Tín dụng"),
    ("Tín dụng", "giải ngân bị lỗi", "Giải ngân khoản vay lỗi", "P.Tín dụng"),
    ("Tín dụng", "tính toán lãi suất sai", "Lãi suất tính sai trên hệ thống", "P.Tín dụng"),
    ("Tín dụng", "đóng khoản vay trước hạn", "Đóng tất toán khoản vay trước hạn", "P.Tín dụng"),
    ("Tín dụng", "tái cơ cấu khoản vay", "Tái cơ cấu/gia hạn khoản vay", "P.Tín dụng"),
    ("Tín dụng", "báo cáo nợ xấu", "Báo cáo nợ xấu/NPL", "P.Tín dụng"),
    ("Tín dụng", "phân loại nợ nhóm 12345", "Phân loại nợ nhóm 1-5 sai", "P.Tín dụng"),
    ("Tín dụng", "CIC tra cứu lỗi", "Tra cứu CIC (Credit Information Center) lỗi", "P.Tín dụng"),
    ("Tín dụng", "bảo lãnh ngân hàng", "Phát hành bảo lãnh (L/G) lỗi", "P.Tín dụng"),
    ("Tín dụng", "L/C thư tín dụng", "L/C (Letter of Credit) lỗi", "P.Thanh toán Quốc tế"),
    ("Tín dụng", "tài sản đảm bảo TSĐB", "Tài sản đảm bảo đăng ký sai", "P.Tín dụng"),
    ("Tín dụng", "thu hồi nợ", "Thu hồi nợ/xử lý tài sản đảm bảo", "P.Tín dụng"),
    ("Tín dụng", "xếp hạng tín dụng rating", "Xếp hạng khách hàng (rating) lỗi", "P.Tín dụng"),
    ("Tín dụng", "hạn mức tín dụng limit", "Hạn mức tín dụng sai/hết hạn mức", "P.Tín dụng"),
    ("Tín dụng", "phê duyệt đa cấp", "Phê duyệt đa cấp bị kẹt", "P.Tín dụng"),
    ("Tín dụng", "đề nghị tạm ứng", "Tạm ứng vốn lỗi", "P.Tín dụng"),
    ("Tín dụng", "báo cáo dư nợ", "Báo cáo dư nợ sai/không cập nhật", "P.Tín dụng"),
    # === AML / Phòng chống rửa tiền (12) ===
    ("AML", "giao dịch đáng ngờ AML alert", "Alert AML giao dịch đáng ngờ", "P.AML"),
    ("AML", "báo cáo AML CTR STR", "Báo cáo CTR/STR (giao dịch đáng ngờ)", "P.AML"),
    ("AML", "screening PEP check", "Kiểm tra PEP (Politically Exposed Person)", "P.AML"),
    ("AML", "blacklist match trùng", "Khách hàng trùng blacklist", "P.AML"),
    ("AML", "sanctions check trừng phạt", "Kiểm tra sanctions OFAC/UN", "P.AML"),
    ("AML", "KYC cập nhật", "Cập nhật KYC (Know Your Customer)", "P.AML"),
    ("AML", "customer due diligence CDD", "Customer Due Diligence (CDD) lỗi", "P.AML"),
    ("AML", "transaction monitoring alert", "Transaction monitoring alert", "P.AML"),
    ("AML", "STR báo cáo", "Suspicious Transaction Report", "P.AML"),
    ("AML", "AML name screening false positive", "Name screening false positive", "P.AML"),
    ("AML", "KYC tài liệu hết hạn", "KYC tài liệu khách hàng hết hạn", "P.AML"),
    ("AML", "rủi ro quốc gia high risk", "Khách hàng quốc gia high risk", "P.AML"),
    # === Quản lý Rủi ro (10) ===
    ("Quản lý Rủi ro", "báo cáo rủi ro tín dụng", "Báo cáo rủi ro tín dụng", "P.Quản lý Rủi ro"),
    ("Quản lý Rủi ro", "rủi ro thanh khoản", "Rủi ro thanh khoản (liquidity risk)", "P.Quản lý Rủi ro"),
    ("Quản lý Rủi ro", "rủi ro thị trường", "Rủi ro thị trường (market risk)", "P.Quản lý Rủi ro"),
    ("Quản lý Rủi ro", "rủi ro vận hành", "Rủi ro vận hành (operational risk)", "P.Quản lý Rủi ro"),
    ("Quản lý Rủi ro", "stress testing", "Stress testing/kịch bản áp lực", "P.Quản lý Rủi ro"),
    ("Quản lý Rủi ro", "basel reporting", "Báo cáo Basel III", "P.Quản lý Rủi ro"),
    ("Quản lý Rủi ro", "IFRS 9 ECL", "Tính toán ECL theo IFRS 9", "P.Quản lý Rủi ro"),
    ("Quản lý Rủi ro", "limit hạn mức rủi ro", "Hạn mức rủi ro sai", "P.Quản lý Rủi ro"),
    ("Quản lý Rủi ro", "vaR tính toán", "VaR (Value at Risk) tính sai", "P.Quản lý Rủi ro"),
    ("Quản lý Rủi ro", "báo cáo NHNN rủi ro", "Báo cáo NHNN về rủi ro", "P.Quản lý Rủi ro"),
    # === Kiểm soát Nội bộ (8) ===
    ("Kiểm soát", "kiểm toán đột xuất", "Kiểm toán đột xuất", "P.Kiểm soát Nội bộ"),
    ("Kiểm soát", "báo cáo kiểm soát", "Báo cáo kiểm soát nội bộ", "P.Kiểm soát Nội bộ"),
    ("Kiểm soát", "đánh giá tuân thủ", "Đánh giá tuân thủ quy trình", "P.Kiểm soát Nội bộ"),
    ("Kiểm soát", "SOC report", "SOC report lỗi", "P.Kiểm soát Nội bộ"),
    ("Kiểm soát", "phát hiện gian lận", "Phát hiện gian lận/sai sót", "P.Kiểm soát Nội bộ"),
    ("Kiểm soát", "kiểm soát chi nhánh", "Kiểm soát tại chi nhánh", "P.Kiểm soát Nội bộ"),
    ("Kiểm soát", "đề xuất khắc phục", "Đề xuất khắc phục sau kiểm soát", "P.Kiểm soát Nội bộ"),
    ("Kiểm soát", "follow up recommendation", "Follow up recommendation sau audit", "P.Kiểm soát Nội bộ"),
    # === Giao dịch / Counter (12) ===
    ("Giao dịch", "giao dịch viên lỗi hệ thống", "GDV không thao tác được", "P.Giao dịch"),
    ("Giao dịch", "in sổ tiết kiệm", "In sổ tiết kiệm lỗi", "P.Giao dịch"),
    ("Giao dịch", "chuyển khoản nội bộ", "Chuyển khoản nội bộ lỗi", "P.Giao dịch"),
    ("Giao dịch", "nộp rút tiền mặt", "Nộp/rút tiền mặt lỗi", "P.Giao dịch"),
    ("Giao dịch", "gửi tiền tiết kiệm", "Gửi tiền tiết kiệm lỗi", "P.Giao dịch"),
    ("Giao dịch", "mở tài khoản mới", "Mở tài khoản khách hàng mới", "P.Giao dịch"),
    ("Giao dịch", "đóng tài khoản", "Đóng tài khoản khách hàng", "P.Giao dịch"),
    ("Giao dịch", "sửa thông tin tài khoản", "Sửa thông tin tài khoản khách", "P.Giao dịch"),
    ("Giao dịch", "phí giao dịch", "Phí giao dịch tính sai", "P.Giao dịch"),
    ("Giao dịch", "kiểm tra số dư", "Kiểm tra số dư khách hàng", "P.Giao dịch"),
    ("Giao dịch", "in xác nhận giao dịch", "In xác nhận giao dịch lỗi", "P.Giao dịch"),
    ("Giao dịch", "chuyển tiền 247 nhanh", "Chuyển tiền nhanh 247 lỗi", "P.Giao dịch"),
    # === Kho quỹ / Treasury (10) ===
    ("Kho quỹ", "đếm tiền mặt", "Đếm tiền mặt cuối ca", "P.Kho quỹ"),
    ("Kho quỹ", "xuất nhập quỹ", "Xuất/nhập quỹ lỗi", "P.Kho quỹ"),
    ("Kho quỹ", "báo cáo quỹ", "Báo cáo quỹ cuối ngày", "P.Kho quỹ"),
    ("Kho quỹ", "cân đối quỹ cuối ngày", "Cân đối quỹ không khớp", "P.Kho quỹ"),
    ("Kho quỹ", "tiền mặt thừa thiếu", "Tiền mặt thừa/thiếu", "P.Kho quỹ"),
    ("Kho quỹ", "chuyển tiền chi nhánh", "Chuyển tiền giữa chi nhánh", "P.Kho quỹ"),
    ("Kho quỹ", "bảo hiểm tiền mặt", "Bảo hiểm tiền mặt vận chuyển", "P.Kho quỹ"),
    ("Kho quỹ", "ATM nạp tiền", "Nạp tiền ATM", "P.Kho quỹ"),
    ("Kho quỹ", "kiểm kê quỹ", "Kiểm kê quỹ định kỳ", "P.Kho quỹ"),
    ("Kho quỹ", "soi tiền giả", "Phát hiện tiền giả", "P.Kho quỹ"),
    # === Pháp chế / Compliance (10) ===
    ("Pháp chế", "hợp đồng pháp lý", "Soạn/kiểm tra hợp đồng pháp lý", "P.Pháp chế"),
    ("Pháp chế", "kiểm tra tuân thủ", "Kiểm tra tuân thủ quy định", "P.Pháp chế"),
    ("Pháp chế", "giấy phép NHNN", "Giấy phép NHNN hết hạn/cấp mới", "P.Pháp chế"),
    ("Pháp chế", "báo cáo NHNN", "Báo cáo NHNN (Ngân hàng Nhà nước)", "P.Pháp chế"),
    ("Pháp chế", "văn bản pháp lý", "Ban hành văn bản pháp lý", "P.Pháp chế"),
    ("Pháp chế", "soạn thảo hợp đồng", "Soạn thảo hợp đồng tín dụng", "P.Pháp chế"),
    ("Pháp chế", "kiểm tra điều khoản", "Kiểm tra điều khoản hợp đồng", "P.Pháp chế"),
    ("Pháp chế", "kiện tụng giải quyết tranh chấp", "Giải quyết tranh chấp kiện tụng", "P.Pháp chế"),
    ("Pháp chế", "tuân thủ Basel", "Tuân thủ Basel III", "P.Pháp chế"),
    ("Pháp chế", "báo cáo lưu động tiền", "Báo cáo lưu động tiền (CTR)", "P.Pháp chế"),
    # === Chăm sóc Khách hàng (10) ===
    ("CSKH", "khiếu nại khách hàng", "Tiếp nhận khiếu nại khách hàng", "P.Chăm sóc Khách hàng"),
    ("CSKH", "hotline 247", "Hotline 24/7 không nhận được", "P.Chăm sóc Khách hàng"),
    ("CSKH", "refund hoàn tiền", "Yêu cầu hoàn tiền/refund", "P.Chăm sóc Khách hàng"),
    ("CSKH", "tra cứu giao dịch", "Tra cứu giao dịch cho khách", "P.Chăm sóc Khách hàng"),
    ("CSKH", "đổi thẻ mất", "Khách báo mất thẻ, cần khóa đổi", "P.Chăm sóc Khách hàng"),
    ("CSKH", "khôi phục tài khoản", "Khôi phục tài khoản bị khóa", "P.Chăm sóc Khách hàng"),
    ("CSKH", "survey khảo sát", "Khảo sát mức độ hài lòng KH", "P.Chăm sóc Khách hàng"),
    ("CSKH", "ticket complaint", "Tạo ticket complaint khách hàng", "P.Chăm sóc Khách hàng"),
    ("CSKH", "giao dịch sai cần hoàn", "Giao dịch sai cần hoàn tiền", "P.Chăm sóc Khách hàng"),
    ("CSKH", "thông tin saler lỗi", "Sale nhập sai thông tin KH", "P.Chăm sóc Khách hàng"),
    # === Marketing (6) ===
    ("Marketing", "campaign SMS", "Gửi SMS campaign lỗi", "P.Marketing"),
    ("Marketing", "push notification", "Push notification app lỗi", "P.Marketing"),
    ("Banner website", "banner website", "Đổi banner website lỗi", "P.Marketing"),
    ("Marketing", "chương trình khuyến mãi", "Cấu hình khuyến mãi lỗi", "P.Marketing"),
    ("Marketing", "email marketing", "Gửi email marketing lỗi", "P.Marketing"),
    ("Marketing", "báo cáo campaign", "Báo cáo hiệu quả campaign", "P.Marketing"),
    # === Mua hàng / Procurement (6) ===
    ("Mua hàng", "mua thiết bị IT", "Đề nghị mua thiết bị IT", "P.Mua hàng"),
    ("Mua hàng", "hợp đồng nhà cung cấp", "Hợp đồng nhà cung cấp", "P.Mua hàng"),
    ("Mua hàng", "đề nghị mua hàng", "Đề nghị mua hàng (PR)", "P.Mua hàng"),
    ("Mua hàng", "báo giá", "Yêu cầu báo giá", "P.Mua hàng"),
    ("Mua hàng", "kiểm tra chất lượng", "Kiểm tra chất lượng hàng hóa", "P.Mua hàng"),
    ("Mua hàng", "quản lý kho", "Quản lý kho/vật tư", "P.Mua hàng"),
    # === Tài chính / Đầu tư (8) ===
    ("Tài chính", "báo cáo đầu tư", "Báo cáo đầu tư", "P.Tài chính Đầu tư"),
    ("Tài chính", "treasury dealing", "Treasury dealing lỗi", "P.Tài chính Đầu tư"),
    ("Tài chính", "forex giao dịch", "Giao dịch forex lỗi", "P.Tài chính Đầu tư"),
    ("Tài chính", "trái phiếu", "Giao dịch trái phiếu", "P.Tài chính Đầu tư"),
    ("Tài chính", "chứng khoán", "Giao dịch chứng khoán", "P.Tài chính Đầu tư"),
    ("Tài chính", "hedge phòng hộ", "Giao dịch hedge/phòng hộ", "P.Tài chính Đầu tư"),
    ("Tài chính", "NOSTRO vị trí", "Quản lý vị trí NOSTRO", "P.Tài chính Đầu tư"),
    ("Tài chính", "báo cáo ALM", "Báo cáo ALM (Asset Liability Management)", "P.Tài chính Đầu tư"),
    # === Phát triển Sản phẩm (6) ===
    ("Phát triển SP", "tạo sản phẩm mới", "Tạo sản phẩm ngân hàng mới", "P.Phát triển Sản phẩm"),
    ("Phát triển SP", "cấu hình sản phẩm", "Cấu hình sản phẩm trên core", "P.Phát triển Sản phẩm"),
    ("Phát triển SP", "test sản phẩm UAT", "Test UAT sản phẩm mới", "P.Phát triển Sản phẩm"),
    ("Phát triển SP", "launch sản phẩm", "Triển khai sản phẩm mới", "P.Phát triển Sản phẩm"),
    ("Phát triển SP", "báo cáo hiệu quả SP", "Báo cáo hiệu quả sản phẩm", "P.Phát triển Sản phẩm"),
    ("Phát triển SP", "điều chỉnh lãi suất", "Điều chỉnh lãi suất sản phẩm", "P.Phát triển Sản phẩm"),
    # === Ngân hàng Số / Digital (10) ===
    ("NH Số", "eKYC lỗi", "eKYC xác thực lỗi", "P.Ngân hàng Số"),
    ("NH Số", "QR pay lỗi", "QR pay không hoạt động", "P.Ngân hàng Số"),
    ("NH Số", "mobile banking đăng ký", "Đăng ký mobile banking lỗi", "P.Ngân hàng Số"),
    ("NH Số", "token soft lỗi", "Soft token app lỗi", "P.Ngân hàng Số"),
    ("NH Số", "smart OTP", "Smart OTP không nhận", "P.Ngân hàng Số"),
    ("NH Số", "faceID xác thực", "FaceID lỗi", "P.Ngân hàng Số"),
    ("NH Số", "liên kết tài khoản", "Liên kết tài khoản lỗi", "P.Ngân hàng Số"),
    ("NH Số", "open API", "Open API lỗi", "P.Ngân hàng Số"),
    ("NH Số", "biometric lỗi", "Biometric không xác thực được", "P.Ngân hàng Số"),
    ("NH Số", "payment gateway lỗi", "Payment gateway lỗi", "P.Ngân hàng Số"),
    # === Dữ liệu / BI (8) ===
    ("Dữ liệu/BI", "báo cáo BI dashboard", "BI dashboard lỗi/không load", "P.Dữ liệu & BI"),
    ("Dữ liệu/BI", "ETL pipeline lỗi", "ETL pipeline fail", "P.Dữ liệu & BI"),
    ("Dữ liệu/BI", "data warehouse chậm", "Data warehouse query chậm", "P.Dữ liệu & BI"),
    ("Dữ liệu/BI", "báo cáo regulator", "Báo cáo regulator sai", "P.Dữ liệu & BI"),
    ("Dữ liệu/BI", "data quality lỗi", "Data quality check fail", "P.Dữ liệu & BI"),
    ("Dữ liệu/BI", "tableau powerBI", "Tableau/PowerBI lỗi", "P.Dữ liệu & BI"),
    ("Dữ liệu/BI", "data pipeline schedule", "Data pipeline schedule lỗi", "P.Dữ liệu & BI"),
    ("Dữ liệu/BI", "migration dữ liệu", "Migration dữ liệu lỗi", "P.Dữ liệu & BI"),
    # === Vận hành (8) ===
    ("Vận hành", "ca trực lỗi", "Ca trực vận hành lỗi", "P.Vận hành"),
    ("Vận hành", "monitoring alert", "Monitoring alert hệ thống", "P.Vận hành"),
    ("Vận hành", "incident P1 P2", "Incident P1/P2 cần xử lý", "P.Vận hành"),
    ("Vận hành", "change request CR", "Change request (CR) triển khai", "P.Vận hành"),
    ("Vận hành", "runbook thủ tục", "Runbook/thủ tục vận hành", "P.Vận hành"),
    ("Vận hành", "capacity planning", "Capacity planning", "P.Vận hành"),
    ("Vận hành", "DR failover", "Disaster recovery failover", "P.Vận hành"),
    ("Vận hành", "báo cáo SLA", "Báo cáo SLA/giám sát", "P.Vận hành"),
]

def main():
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = "Dau_moi"
    headers = ["STT", "Nhom_van_de", "Tu_khoa", "Mo_ta", "Phong_ban",
               "Nguoi_dau_moi", "Chuc_vu", "Email", "Teams", "Dien_thoai"]
    ws.append(headers)
    for c in ws[1]:
        c.font = Font(bold=True, color="FFFFFF")
        c.fill = PatternFill("solid", fgColor="1F4E78")
        c.alignment = Alignment(horizontal="center", vertical="center")
    for i, (nhom, tukhoa, mota, phong) in enumerate(ROWS, start=1):
        nguoi, chucvu, email, teams, dt = DEPARTMENTS[phong]
        ws.append([i, nhom, tukhoa, mota, phong, nguoi, chucvu, email, teams, dt])
    widths = [5, 16, 34, 40, 26, 18, 20, 26, 20, 16]
    for idx, w in enumerate(widths, start=1):
        ws.column_dimensions[openpyxl.utils.get_column_letter(idx)].width = w
    ws.freeze_panes = "A2"
    out = "contacts.xlsx"
    wb.save(out)
    print(f"Created {out} with {len(ROWS)} rows.")

if __name__ == "__main__":
    main()
